# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Guilan
tagline:             '作品集'
description:         '瑰澜的作品集'
url:                 guilanart.github.io
baseurl:             'https://guilanart.github.io'
paginate:            5

# About/contact
author:
  name:              Guilan
  # url:               https://twitter.com/mdo
  email:             guilan@guilanart.com

# Custom vars
version:             1.0.0
